### PR TITLE
Removing Conditional Logic

### LINKED ISSUE #461: Redirect web part fails if there are specific permissions on list items
## Category

- [x] Bug

## Describe the bug
The Redirect extension works correctly when both the "PnP Redirect Links" list and list items therein do not have their permissions modified.
When list items have specific permissions (i.e. breaking inheritance and applying specific permissions to list items) then the Redirect extension fails. 

#### Expected or Desired Behavior

Expected that the Redirect continues to work even with specific list item security.

#### Observed Behavior

Redirect fails with console message "Failed to create custom list PnP Redirect Links" when item level security is applied.

#### Steps to Reproduce

Install the Redirect extension and let it create the custom list.
Create two list items, each with same source URL and different destination URL's
Go to the source URL - Redirects correctly on the first "found" item.

Now, stop inheriting permissions on each item and only allow members of specific groups to see the list items.
When user logs in they can navigate to the custom list and they will only see ONE of the two items.

Redirect now fails with console message "Failed to create custom list PnP Redirect Links"

NOTE:  I have determined that the bug appears to be in the this line:
```
       const ensureResult: ListEnsureResult = await sp.web.lists.ensure(redirectionsListTitle,
       'Redirections',
        100,
        true);
```
The "ensure" method fails, even though the list exists for the user.

My workaround is to 
a) allow the default extension to create the list in the first place
b) replace line 67
```
   if (await this.ensureRedirectionsList(redirectionsListTitle)) 
```
with
```
   if (true)
```
then build a new version of the extension 
then deploy the extension

## Environment Details (*Development & Target environment*)

SharePoint online

### PR DESCRIPTION
**Pull request by bcameron1231**
Removing Conditional Logic for EnsureRedirectionsList. This method uses the csom ensure() method, which is intended to find a list and create it if it doesn't exist. However, it requires elevated permissions to run. As a result, users with Read permissions to the Redirection List cannot use this redirect functionality. 

I removed the if statement wrapping this method, and added a catch for logging the error. Users with permission will be able to execute this. Read only users it will silently fail with a 403, and then continue processing under the assumption that the list is already created.

#### Category
- [x] Bug Fix
- [ ] New Feature
- Related issues: fixes #461

#### What's in this Pull Request?
Removal of conditional logic to support read permission users.

#### Guidance
To test run the extension as a user with minimum manage web permissions to create the Redirect List. Test to makes sure the redirects work. Subsequently, login with a read only user and make sure the redirect works.

### CODE REVIEW

**Comment by bcameron1231** [comment]
@eoverfield, so I'm not 100% sure the best overall fix for this implementation and looking for your recommendation.  This is a quick fix that supports the original intent of the ensure functionality. As this list isn't provisioned with the PnP Template, the only way the list gets created is manually or by using the ensure functionality.

Because the Ensure functionality requires elevated permissions and included a conditional if block, read only users were unable to use the redirect extension. By removing the If block, it will silently fail for the Read Only users, and then continue processing assuming the list has already been created. 

I don't *love* it.  But it may be worth exploring the simplification of the code and the removal of the ensure() code, and providing the deployment of the list via the provisioning template instead. Then making the assumption in code that the list has already been deployed correctly.

**Comment by eoverfield** [comment]
I am good with the approach. What I like about using pnpjs's ensure() method here is its use as a technology demonstrator. I would like to keep it, and moving that to its own block is good to me.

I suggest adding a try block around the new if(await ensured) as if that fails, doesn't it throw an error, not just a false? I haven't tested, just a thought. If not an issue, let's merge and then we can update the sppkg and the pnp package.

**Comment by bcameron1231** [comment]
Hi Eric, thanks so much for the feedback. In my code, I removed the If block as it wouldn't execute for read-only. The Ensure method does indeed throw an error if an error happens, and so I added a catch onto the ensureRedirectionsList() method in the event that Ensure() throws an error back. I am catching the error and logging it for diagnostic purposes.  

We should be good to go.

**Comment by eoverfield** [comment]
Ah, of course, the try is in that method. Nice, thanks!

**Pull request merged**
