### PR TITLE
Fix section web part background

### LINKED ISSUE #323: Personal Calendar & the Recently Visited Sites web parts don't get the background color of the section they're on
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Both the Personal Calendar & the Recently Visited Sites web parts don't get the background color of the section. I would expect them to get the same background color.

#### Observed Behavior

Both the Personal Calendar & the Recently Visited Sites web parts don't get the background color of the section. 

#### Steps to Reproduce

Add the web parts to a section and change the color to something not white.

### PR DESCRIPTION
**Pull request by patrikhellgren**
#### Category
- [x] Bug Fix
- [ ] New Feature
- Related issues: fixes #323 

#### What's in this Pull Request?
Added support for section backgrounds to all webparts.

### CODE REVIEW

**Comment by patrikhellgren** [comment]
@eoverfield I understand that this PR is not valid anymore with the new webpart projects in place but we still need support for section backgrounds in them. Would I have any luck in getting this merged if I ported it to the new webpart project in Starter Kit V2?

**Comment by eoverfield** [comment]
@patrikhellgren Yeah, I apologize for the delay in this as it didn't get added into V1 before the conversion to V2. Your contributions are absolutely appreciated.

The large PR's that hit all webparts are very challenging for us to process. My suggestion, if you are willing, is to pick one webpart to start. Make the suggested update you want and submit a PR. Give the community an opportunity to submit any feedback / recommendations. We can then merge that in, as well as update the general provisioning template to include that as well. Then we could look to burn through all of the webparts.

Would that work for you?

Thanks!

**Comment by StfBauer** [comment]
@patrikhellgren @eoverfield You do not specify a section background as inline style these should be removed. There current version only needs the setting of  "supportsThemeVariants": true

Documentation will be updated soon but is currently not accurate.

**Comment by eoverfield** [comment]
@StfBauer thank you for the clarification. @patrikhellgren I would suggest you see if the supportsThemeVariants setting in the webpart manifest delivers what you are looking for. The Personal Tasks webpart already does include this. If this isn't what you are looking for, let's continue the discussion here.

**Comment by patrikhellgren** [comment]
@StfBauer Thank you for the info, that was enough to get it working. For how long has this been working this way? Or has the documentation ([Supporting section backgrounds](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds)) always been inaccurate?

@eoverfield The Personal Tasks webpart uses the same way to handle section theming as I had implemented in this PR so that is not really valid according to what @StfBauer suggested and which seems to be working. Should I then make the change in the rest of the webparts (including Personal Tasks) and submit one PR per webpart or how would you like me to proceed?

**Comment by StfBauer** [comment]
@patrikhellgren I guess it was always working this way but because people read the documentation used it this way. The future will move to a documentation more like the described method here.
https://n8d.at/develop-spfx-web-parts-for-different-section-designs-using-css/

**Comment by patrikhellgren** [comment]
@eoverfield maybe you missed my question above, at least I never got an answer to how you want us to proceed with the section background update. I now thought I would make a PR for at least one of the webparts to get things going but then I notice that a lot of them has been reverted from SPFx 1.9.1 to 1.4.1. I guess this has to do with 2019 support. So since "supportsThemeVariants" was added in 1.8 this is now a no go.

Since some of the webparts is on at least 1.9.1 and able to support "supportsThemeVariants" we would get an inconsistent look on the different webparts and the 1.4.1 ones doesn't look good in a modern intranet using different section backgrounds.

What is your idea on how to move forward with this?

**Pull request closed without merging**
