### PR TITLE
Added a CodeTour to the project

### PR DESCRIPTION
**Pull request by hugoabernier**
#### Category
- [ ] Bug Fix
- [x] New Feature

#### What's in this Pull Request?

Added a [CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) to the solution. If you like this, we'll add more CodeTours for every web part, and one for deployment.

The CodeTour does not affect the solution (with the exception of a `.tours` folder. If users don't have the CodeTour extension installed, nothing will happen. However, if they have the extension installed, it will invite users to view the tour when they open the solution.

### CODE REVIEW

**Comment by bcameron1231** [comment]
@eoverfield,

@hugoabernier @PopWarner  and I spend some time setting up our initial code tour for the Starter Kit tonight. We have plans of expanding this out to include tours of individual spfx solution. But this is the first set up, exploring the solution root level folders.

**Comment by eoverfield** [comment]
Awesome! Thank you very much. Tours of each individual part would be outstanding and very useful for the community. Thanks, and please add whatever you can.

**Comment by eoverfield** [comment]
Do you have a snippet of text we could add to the root readme to help guide new devs to this extension? etc?

**Comment by bcameron1231** [comment]
Yes. I can make an update to the readme to include this information!

**Pull request merged**
