### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by bcameron1231**
Adding new issue templates to better match other PnP Repository for Bugs/Enhancements/Questions.

### CODE REVIEW

**Comment by eoverfield** [comment]
@bcameron1231 We will want to focus our efforts on V2 once it is released, yet for a while we would like to assist with legacy v1 questions if possible. Let's add to the templates a request as to which version of the kit they are using as we would have to ask this anyhow for many general questions, even if just to confirm. Thanks.

**Comment by bcameron1231** [comment]
@eoverfield  Sounds good. Would you like it just as a selection (like the 'x' check box) as the first option?

**Comment by eoverfield** [comment]
Id suggest one of the text fields to fill out, that way we could expand later, and also provide suggestion text.
Starter kit version: (i.e. v2 for current version, v1 for legacy solution)

or something like that.

**Comment by bcameron1231** [comment]
Sounds good. I've added it to the Bug template. I'm not sure if we need it on the Question/Enhancement template, as we'd only accept enhancements and such on the V2 source. What do you think?

**Comment by eoverfield** [comment]
Oh yes, fair point. We can only support bugs or installation issues for V1 moving forward. And I can't say we would for sure be able to address new bugs, but let's get them reported if they exist so we can timebox. Thanks.

**Pull request merged**
