### PR TITLE
Updates the Personal Calendar web part to use MGT React. Closes partially #452

### PR DESCRIPTION
**Pull request by waldekmastykarz**
Updates the Personal Calendar web part to use MGT React. Closes partially #452

#### Category
- [ ] Bug Fix
- [ ] New Feature
- Related issues: partially #452

#### What's in this Pull Request?

Updates the Personal Calendar web part to use Microsoft Graph Toolkit React

### CODE REVIEW

**Comment by eoverfield** [comment]
@waldekmastykarz generally the PR looks excellent. Seeing the code simplify is what we want.

Would you please try adding a page that includes both the updated personal tasks and this PR. When I have one page with both new webparts, I am seeing an error:

Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry

My guess is how this has to be registered in the code, the toolkit is doing something off?

In the meantime I will be submitting a commit that includes updated documentation for how to build this webpart with the library.

**Comment by waldekmastykarz** [comment]
@eoverfield that's odd. I've tested the updated web part with hosted workbench and haven't seen this issue. Let me have another look to see if I can reproduce it.

**Comment by eoverfield** [comment]
@waldekmastykarz I went ahead and merged this into master as I also included updated documentation for building the webpart with considerations for the library component. If you are able to duplicate the bug with having multiple mgr driven webparts on the same page, and provide a fix, would you please submit a new PR? Thanks for the outstanding work.

**Comment by waldekmastykarz** [comment]
Will do. Thank you! Looking back at your comment, I missed that the issue occurs with both web parts on the page. Thank you for clarifying it. I'll have a look at it and will definitely submit a PR if when I find out what's wrong.

**Comment by waldekmastykarz** [comment]
Hey @eoverfield, I can repro the issue and I suspect it's coming from Microsoft Graph Toolkit. I'll create an issue there and hopefully we'll be able to get it fixed clearly. I'll post an update here as soon as I know more.

**Comment by waldekmastykarz** [comment]
Sitrep: we've identified the problem and are working on integrating the solution with MGT. Once the work is complete, we'll update the docs and will submit a PR here to patch the packages.

**Comment by bcameron1231** [comment]
Just checking in to see if there's been any progress on this @waldekmastykarz ?

**Comment by waldekmastykarz** [comment]
Yes, together with the MGT team we're working on a solution. We should have it available shortly.

**Comment by waldekmastykarz** [comment]
Good news! It took us a bit longer than planned, but the Microsoft Graph Toolkit team has just released a v2.2 of MGT with support for using MGT in SPFx without any limitations. We should update the solution to use the new setup and could then pickup the upgrade process.

**Comment by eoverfield** [comment]
Outstanding news @waldekmastykarz , I'll add to my list, though @bcameron1231, don't let me slow you down if you have bandwidth.

**Comment by bcameron1231** [comment]
This is great news! I have some shelved changesets with MGT components already... and I can try and find some time to update and test the solution.

**Pull request merged**
