### PR TITLE
Upgrades Personal Tasks web part to use MGT React. Related to #452

### PR DESCRIPTION
**Pull request by waldekmastykarz**
#### Category
- [ ] Bug Fix
- [ ] New Feature
- Related issues: partially #452

Upgrades Personal Tasks web part to use MGT React. Related to #452

### CODE REVIEW

**Comment by bcameron1231** [comment]
Thanks @waldekmastykarz ! I took a look, and things are looking good -- both Planner and To-Do functionality appear to be functioning correctly. 

One change request I have is on the Planner side, can you update to include a TaskFilter for the current user? 

Currently, the tasks are pulling for all users in that plan/bucket and should be showing tasks for the current user. This may also warrant a larger discussion around the performance of this web part, as it's going to load all tasks and then do a post filter.  Though, I'm not overly concerned about that as this is a demo solution.

**Comment by bcameron1231** [comment]
@waldekmastykarz .... I'll apologize first, it looks like we missed this originally during our transition to V2. When it was originally moved to MGT last year, it appears that PR didn't filter tasks by the current user... 


Is it possible to add this filter back in? :)

**Comment by waldekmastykarz** [comment]
Shall we add it after the merge and release it gradually?

**Comment by bcameron1231** [comment]
That's completely fine! Everything looks good then!  

To be honest, this might be something worth re-branding this web part to just be a Task Display instead of "personal". Given that we have the filters for finding personal tasks and other plans as well.

What do you think about potentially re-branding this web part @eoverfield ?

**Comment by eoverfield** [comment]
If we are going to add the personal aspect soon, i.e in weeks, not months, I would rather we keep the branding as is, which notes in the readme to state the expected output. As a demo solution, this is reasonable. I would like to get the current PR confirmed and merged though as soon as we can to get broader input.

I had not intended to update starterkit.pnp though until we have all graph enabled webparts updated, allowing up to maintain a consistent, stable provisioning kit, while also allowing for enhanced features via the updated webparts. Seeking input on this strategy as well.

**Comment by bcameron1231** [comment]
Great! I'll proceed to finish my testing on this and the calendar sample! Thanks!

**Comment by eoverfield** [comment]
@bcameron1231 in testing out the webpart, when I do not select "hide filter", I do get the ability to filter by current user, or all tasks. Is this the feature you are looking for? This appeared to work for me when I allowed for all of my tasks, or only to show tasks within a specific plan or bucket

**Comment by eoverfield** [comment]
I have completed the merge, Thank you @waldekmastykarz. I increased the version number of the package, also added more documentation in the webparts readme. @bcameron1231 if you have more edits or suggestions, we can push any additional commits in then.

**Comment by bcameron1231** [comment]
@eoverfield  Yea that filter is available, and works great. I think my concern was... when you provide the plan id, it doesn't filter by the current user by default and requires the user to select the filter.... which is why I thought a "re-brand" would make sense since the web part isn't just "personal tasks" anymore. :) But totally cool keeping it as is!

**Comment by eoverfield** [comment]
@bcameron1231 ok, as in this webpart is more for "Tasks" rather than personal tasks. It does seem as though the default for any source, be it planner, a specific plan, etc, should be consistent. I'd ask that someone take lead on this, make a cohesive change, update the solution webpart readme, and submit a PR so we can test it out.

**Pull request merged**
